// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/ctsmTMB.h"
#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ekf_filter_rcpp
List ekf_filter_rcpp(List funPtrs, const Eigen::MatrixXd& obsMat, const Eigen::MatrixXd& inputMat, const Eigen::VectorXd& parVec, Eigen::MatrixXd covMat, Eigen::VectorXd stateVec, const Eigen::VectorXd& ode_timestep_size, const Eigen::VectorXd& ode_timesteps, LogicalVector any_available_obs, List non_na_ids, const int ode_solver);
RcppExport SEXP _ctsmTMB_ekf_filter_rcpp(SEXP funPtrsSEXP, SEXP obsMatSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP covMatSEXP, SEXP stateVecSEXP, SEXP ode_timestep_sizeSEXP, SEXP ode_timestepsSEXP, SEXP any_available_obsSEXP, SEXP non_na_idsSEXP, SEXP ode_solverSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type obsMat(obsMatSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type covMat(covMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type stateVec(stateVecSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ode_timestep_size(ode_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ode_timesteps(ode_timestepsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type any_available_obs(any_available_obsSEXP);
    Rcpp::traits::input_parameter< List >::type non_na_ids(non_na_idsSEXP);
    Rcpp::traits::input_parameter< const int >::type ode_solver(ode_solverSEXP);
    rcpp_result_gen = Rcpp::wrap(ekf_filter_rcpp(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, any_available_obs, non_na_ids, ode_solver));
    return rcpp_result_gen;
END_RCPP
}
// ekf_predict_rcpp
List ekf_predict_rcpp(List funPtrs, const Eigen::MatrixXd& obsMat, const Eigen::MatrixXd& inputMat, const Eigen::VectorXd& parVec, Eigen::MatrixXd covMat, Eigen::VectorXd stateVec, const Eigen::VectorXd& ode_timestep_size, const Eigen::VectorXd& ode_timesteps, Rcpp::LogicalVector any_available_obs, List non_na_ids, const int ode_solver, const int last_pred_id, const int k_step_ahead);
RcppExport SEXP _ctsmTMB_ekf_predict_rcpp(SEXP funPtrsSEXP, SEXP obsMatSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP covMatSEXP, SEXP stateVecSEXP, SEXP ode_timestep_sizeSEXP, SEXP ode_timestepsSEXP, SEXP any_available_obsSEXP, SEXP non_na_idsSEXP, SEXP ode_solverSEXP, SEXP last_pred_idSEXP, SEXP k_step_aheadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type obsMat(obsMatSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type covMat(covMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type stateVec(stateVecSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ode_timestep_size(ode_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ode_timesteps(ode_timestepsSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type any_available_obs(any_available_obsSEXP);
    Rcpp::traits::input_parameter< List >::type non_na_ids(non_na_idsSEXP);
    Rcpp::traits::input_parameter< const int >::type ode_solver(ode_solverSEXP);
    Rcpp::traits::input_parameter< const int >::type last_pred_id(last_pred_idSEXP);
    Rcpp::traits::input_parameter< const int >::type k_step_ahead(k_step_aheadSEXP);
    rcpp_result_gen = Rcpp::wrap(ekf_predict_rcpp(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, any_available_obs, non_na_ids, ode_solver, last_pred_id, k_step_ahead));
    return rcpp_result_gen;
END_RCPP
}
// ekf_simulate_rcpp
List ekf_simulate_rcpp(List funPtrs, Eigen::MatrixXd obsMat, Eigen::MatrixXd inputMat, Eigen::VectorXd parVec, Eigen::MatrixXd covMat, Eigen::VectorXd stateVec, Eigen::VectorXd ode_timestep_size, Eigen::VectorXd ode_timesteps, Eigen::VectorXd simulation_timestep_size, Eigen::VectorXd simulation_timesteps, Rcpp::LogicalVector any_available_obs, List non_na_ids, const int ode_solver, const int last_pred_id, const int k_step_ahead, const int ng, const int nsims, Nullable<int> seed);
RcppExport SEXP _ctsmTMB_ekf_simulate_rcpp(SEXP funPtrsSEXP, SEXP obsMatSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP covMatSEXP, SEXP stateVecSEXP, SEXP ode_timestep_sizeSEXP, SEXP ode_timestepsSEXP, SEXP simulation_timestep_sizeSEXP, SEXP simulation_timestepsSEXP, SEXP any_available_obsSEXP, SEXP non_na_idsSEXP, SEXP ode_solverSEXP, SEXP last_pred_idSEXP, SEXP k_step_aheadSEXP, SEXP ngSEXP, SEXP nsimsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obsMat(obsMatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type covMat(covMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type stateVec(stateVecSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timestep_size(ode_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timesteps(ode_timestepsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type simulation_timestep_size(simulation_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type simulation_timesteps(simulation_timestepsSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type any_available_obs(any_available_obsSEXP);
    Rcpp::traits::input_parameter< List >::type non_na_ids(non_na_idsSEXP);
    Rcpp::traits::input_parameter< const int >::type ode_solver(ode_solverSEXP);
    Rcpp::traits::input_parameter< const int >::type last_pred_id(last_pred_idSEXP);
    Rcpp::traits::input_parameter< const int >::type k_step_ahead(k_step_aheadSEXP);
    Rcpp::traits::input_parameter< const int >::type ng(ngSEXP);
    Rcpp::traits::input_parameter< const int >::type nsims(nsimsSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(ekf_simulate_rcpp(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, simulation_timestep_size, simulation_timesteps, any_available_obs, non_na_ids, ode_solver, last_pred_id, k_step_ahead, ng, nsims, seed));
    return rcpp_result_gen;
END_RCPP
}
// calculate_filtering_observations
List calculate_filtering_observations(const List filtration_raw, const List funPtrs, Eigen::MatrixXd inputMat, Eigen::VectorXd parVec, int n_obs);
RcppExport SEXP _ctsmTMB_calculate_filtering_observations(SEXP filtration_rawSEXP, SEXP funPtrsSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP n_obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type filtration_raw(filtration_rawSEXP);
    Rcpp::traits::input_parameter< const List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_filtering_observations(filtration_raw, funPtrs, inputMat, parVec, n_obs));
    return rcpp_result_gen;
END_RCPP
}
// lkf_filter_rcpp
List lkf_filter_rcpp(List funPtrs, Eigen::MatrixXd obsMat, Eigen::MatrixXd inputMat, Eigen::VectorXd parVec, Eigen::MatrixXd covMat, Eigen::VectorXd stateVec, Eigen::VectorXd ode_timestep_size, LogicalVector any_available_obs, List non_na_ids);
RcppExport SEXP _ctsmTMB_lkf_filter_rcpp(SEXP funPtrsSEXP, SEXP obsMatSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP covMatSEXP, SEXP stateVecSEXP, SEXP ode_timestep_sizeSEXP, SEXP any_available_obsSEXP, SEXP non_na_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obsMat(obsMatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type covMat(covMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type stateVec(stateVecSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timestep_size(ode_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type any_available_obs(any_available_obsSEXP);
    Rcpp::traits::input_parameter< List >::type non_na_ids(non_na_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(lkf_filter_rcpp(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, any_available_obs, non_na_ids));
    return rcpp_result_gen;
END_RCPP
}
// lkf_predict_rcpp
List lkf_predict_rcpp(List funPtrs, Eigen::MatrixXd obsMat, Eigen::MatrixXd inputMat, Eigen::VectorXd parVec, Eigen::MatrixXd covMat, Eigen::VectorXd stateVec, Eigen::VectorXd ode_timestep_size, LogicalVector any_available_obs, List non_na_ids, const int last_pred_id, const int k_step_ahead);
RcppExport SEXP _ctsmTMB_lkf_predict_rcpp(SEXP funPtrsSEXP, SEXP obsMatSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP covMatSEXP, SEXP stateVecSEXP, SEXP ode_timestep_sizeSEXP, SEXP any_available_obsSEXP, SEXP non_na_idsSEXP, SEXP last_pred_idSEXP, SEXP k_step_aheadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obsMat(obsMatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type covMat(covMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type stateVec(stateVecSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timestep_size(ode_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type any_available_obs(any_available_obsSEXP);
    Rcpp::traits::input_parameter< List >::type non_na_ids(non_na_idsSEXP);
    Rcpp::traits::input_parameter< const int >::type last_pred_id(last_pred_idSEXP);
    Rcpp::traits::input_parameter< const int >::type k_step_ahead(k_step_aheadSEXP);
    rcpp_result_gen = Rcpp::wrap(lkf_predict_rcpp(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, any_available_obs, non_na_ids, last_pred_id, k_step_ahead));
    return rcpp_result_gen;
END_RCPP
}
// lkf_simulate_rcpp
List lkf_simulate_rcpp(List funPtrs, Eigen::MatrixXd obsMat, Eigen::MatrixXd inputMat, Eigen::VectorXd parVec, Eigen::MatrixXd covMat, Eigen::VectorXd stateVec, Eigen::VectorXd ode_timestep_size, Eigen::VectorXd simulation_timestep_size, Eigen::VectorXd simulation_timesteps, LogicalVector any_available_obs, List non_na_ids, int ng, int last_pred_id, int k_step_ahead, int nsims, Nullable<int> seed);
RcppExport SEXP _ctsmTMB_lkf_simulate_rcpp(SEXP funPtrsSEXP, SEXP obsMatSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP covMatSEXP, SEXP stateVecSEXP, SEXP ode_timestep_sizeSEXP, SEXP simulation_timestep_sizeSEXP, SEXP simulation_timestepsSEXP, SEXP any_available_obsSEXP, SEXP non_na_idsSEXP, SEXP ngSEXP, SEXP last_pred_idSEXP, SEXP k_step_aheadSEXP, SEXP nsimsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obsMat(obsMatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type covMat(covMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type stateVec(stateVecSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timestep_size(ode_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type simulation_timestep_size(simulation_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type simulation_timesteps(simulation_timestepsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type any_available_obs(any_available_obsSEXP);
    Rcpp::traits::input_parameter< List >::type non_na_ids(non_na_idsSEXP);
    Rcpp::traits::input_parameter< int >::type ng(ngSEXP);
    Rcpp::traits::input_parameter< int >::type last_pred_id(last_pred_idSEXP);
    Rcpp::traits::input_parameter< int >::type k_step_ahead(k_step_aheadSEXP);
    Rcpp::traits::input_parameter< int >::type nsims(nsimsSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(lkf_simulate_rcpp(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, simulation_timestep_size, simulation_timesteps, any_available_obs, non_na_ids, ng, last_pred_id, k_step_ahead, nsims, seed));
    return rcpp_result_gen;
END_RCPP
}
// test_return_list
Rcpp::List test_return_list(Eigen::MatrixXd a);
RcppExport SEXP _ctsmTMB_test_return_list(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(test_return_list(a));
    return rcpp_result_gen;
END_RCPP
}
// calculate_prediction_observations
Eigen::MatrixXd calculate_prediction_observations(const Eigen::MatrixXd& predMat, const List& funPtrs, const Eigen::MatrixXd& inputMat, const Eigen::VectorXd& parVec, const int n_states, const int n_obs, const int last_pred_id, const int k_ahead, bool compute_dispersion);
RcppExport SEXP _ctsmTMB_calculate_prediction_observations(SEXP predMatSEXP, SEXP funPtrsSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP n_statesSEXP, SEXP n_obsSEXP, SEXP last_pred_idSEXP, SEXP k_aheadSEXP, SEXP compute_dispersionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type predMat(predMatSEXP);
    Rcpp::traits::input_parameter< const List& >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< const int >::type n_states(n_statesSEXP);
    Rcpp::traits::input_parameter< const int >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< const int >::type last_pred_id(last_pred_idSEXP);
    Rcpp::traits::input_parameter< const int >::type k_ahead(k_aheadSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_dispersion(compute_dispersionSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_prediction_observations(predMat, funPtrs, inputMat, parVec, n_states, n_obs, last_pred_id, k_ahead, compute_dispersion));
    return rcpp_result_gen;
END_RCPP
}
// calculate_simulation_observations
List calculate_simulation_observations(const List simulation_raw_states, const List funPtrs, const Eigen::Map<Eigen::MatrixXd>& inputMat_T, const Eigen::Map<Eigen::VectorXd>& parVec, int n_states, int n_obs, int k_ahead, int n_sims, Nullable<int> seed);
RcppExport SEXP _ctsmTMB_calculate_simulation_observations(SEXP simulation_raw_statesSEXP, SEXP funPtrsSEXP, SEXP inputMat_TSEXP, SEXP parVecSEXP, SEXP n_statesSEXP, SEXP n_obsSEXP, SEXP k_aheadSEXP, SEXP n_simsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type simulation_raw_states(simulation_raw_statesSEXP);
    Rcpp::traits::input_parameter< const List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type inputMat_T(inputMat_TSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< int >::type n_states(n_statesSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< int >::type k_ahead(k_aheadSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_simulation_observations(simulation_raw_states, funPtrs, inputMat_T, parVec, n_states, n_obs, k_ahead, n_sims, seed));
    return rcpp_result_gen;
END_RCPP
}
// build_simulation_returnlist
List build_simulation_returnlist(List simulation_raw, NumericVector time_vector, int n_states, int k_ahead, int n_sims);
RcppExport SEXP _ctsmTMB_build_simulation_returnlist(SEXP simulation_rawSEXP, SEXP time_vectorSEXP, SEXP n_statesSEXP, SEXP k_aheadSEXP, SEXP n_simsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type simulation_raw(simulation_rawSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time_vector(time_vectorSEXP);
    Rcpp::traits::input_parameter< int >::type n_states(n_statesSEXP);
    Rcpp::traits::input_parameter< int >::type k_ahead(k_aheadSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    rcpp_result_gen = Rcpp::wrap(build_simulation_returnlist(simulation_raw, time_vector, n_states, k_ahead, n_sims));
    return rcpp_result_gen;
END_RCPP
}
// build_simulation_timelists
List build_simulation_timelists(NumericVector time_vector, int n_forecasts, int k_ahead);
RcppExport SEXP _ctsmTMB_build_simulation_timelists(SEXP time_vectorSEXP, SEXP n_forecastsSEXP, SEXP k_aheadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time_vector(time_vectorSEXP);
    Rcpp::traits::input_parameter< int >::type n_forecasts(n_forecastsSEXP);
    Rcpp::traits::input_parameter< int >::type k_ahead(k_aheadSEXP);
    rcpp_result_gen = Rcpp::wrap(build_simulation_timelists(time_vector, n_forecasts, k_ahead));
    return rcpp_result_gen;
END_RCPP
}
// ukf_filter_rcpp
List ukf_filter_rcpp(List funPtrs, Eigen::MatrixXd obsMat, Eigen::MatrixXd inputMat, Eigen::VectorXd parVec, Eigen::MatrixXd covMat, Eigen::VectorXd stateVec, Eigen::VectorXd ode_timestep_size, Eigen::VectorXd ode_timesteps, Eigen::MatrixXi bool_is_not_na_obsMat, Eigen::VectorXi number_of_available_obs, Eigen::VectorXd ukf_pars, const int ode_solver);
RcppExport SEXP _ctsmTMB_ukf_filter_rcpp(SEXP funPtrsSEXP, SEXP obsMatSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP covMatSEXP, SEXP stateVecSEXP, SEXP ode_timestep_sizeSEXP, SEXP ode_timestepsSEXP, SEXP bool_is_not_na_obsMatSEXP, SEXP number_of_available_obsSEXP, SEXP ukf_parsSEXP, SEXP ode_solverSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obsMat(obsMatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type covMat(covMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type stateVec(stateVecSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timestep_size(ode_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timesteps(ode_timestepsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type bool_is_not_na_obsMat(bool_is_not_na_obsMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type number_of_available_obs(number_of_available_obsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ukf_pars(ukf_parsSEXP);
    Rcpp::traits::input_parameter< const int >::type ode_solver(ode_solverSEXP);
    rcpp_result_gen = Rcpp::wrap(ukf_filter_rcpp(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, bool_is_not_na_obsMat, number_of_available_obs, ukf_pars, ode_solver));
    return rcpp_result_gen;
END_RCPP
}
// ukf_predict_rcpp
List ukf_predict_rcpp(List funPtrs, Eigen::MatrixXd obsMat, Eigen::MatrixXd inputMat, Eigen::VectorXd parVec, Eigen::MatrixXd covMat, Eigen::VectorXd stateVec, Eigen::VectorXd ode_timestep_size, Eigen::VectorXd ode_timesteps, Eigen::MatrixXi bool_is_not_na_obsMat, Eigen::VectorXi number_of_available_obs, Eigen::VectorXd ukf_pars, const int last_pred_id, const int k_step_ahead, const int ode_solver);
RcppExport SEXP _ctsmTMB_ukf_predict_rcpp(SEXP funPtrsSEXP, SEXP obsMatSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP covMatSEXP, SEXP stateVecSEXP, SEXP ode_timestep_sizeSEXP, SEXP ode_timestepsSEXP, SEXP bool_is_not_na_obsMatSEXP, SEXP number_of_available_obsSEXP, SEXP ukf_parsSEXP, SEXP last_pred_idSEXP, SEXP k_step_aheadSEXP, SEXP ode_solverSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obsMat(obsMatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type covMat(covMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type stateVec(stateVecSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timestep_size(ode_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timesteps(ode_timestepsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type bool_is_not_na_obsMat(bool_is_not_na_obsMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type number_of_available_obs(number_of_available_obsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ukf_pars(ukf_parsSEXP);
    Rcpp::traits::input_parameter< const int >::type last_pred_id(last_pred_idSEXP);
    Rcpp::traits::input_parameter< const int >::type k_step_ahead(k_step_aheadSEXP);
    Rcpp::traits::input_parameter< const int >::type ode_solver(ode_solverSEXP);
    rcpp_result_gen = Rcpp::wrap(ukf_predict_rcpp(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, bool_is_not_na_obsMat, number_of_available_obs, ukf_pars, last_pred_id, k_step_ahead, ode_solver));
    return rcpp_result_gen;
END_RCPP
}
// ukf_simulate_rcpp
List ukf_simulate_rcpp(List funPtrs, Eigen::MatrixXd obsMat, Eigen::MatrixXd inputMat, Eigen::VectorXd parVec, Eigen::MatrixXd covMat, Eigen::VectorXd stateVec, Eigen::VectorXd ode_timestep_size, Eigen::VectorXd ode_timesteps, Eigen::VectorXd simulation_timestep_size, Eigen::VectorXd simulation_timesteps, Eigen::MatrixXi bool_is_not_na_obsMat, Eigen::VectorXi number_of_available_obs, Eigen::VectorXd ukf_pars, const int ng, const int last_pred_id, const int k_step_ahead, const int ode_solver, const int nsims, Nullable<int> seed);
RcppExport SEXP _ctsmTMB_ukf_simulate_rcpp(SEXP funPtrsSEXP, SEXP obsMatSEXP, SEXP inputMatSEXP, SEXP parVecSEXP, SEXP covMatSEXP, SEXP stateVecSEXP, SEXP ode_timestep_sizeSEXP, SEXP ode_timestepsSEXP, SEXP simulation_timestep_sizeSEXP, SEXP simulation_timestepsSEXP, SEXP bool_is_not_na_obsMatSEXP, SEXP number_of_available_obsSEXP, SEXP ukf_parsSEXP, SEXP ngSEXP, SEXP last_pred_idSEXP, SEXP k_step_aheadSEXP, SEXP ode_solverSEXP, SEXP nsimsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type funPtrs(funPtrsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obsMat(obsMatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type inputMat(inputMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type parVec(parVecSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type covMat(covMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type stateVec(stateVecSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timestep_size(ode_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ode_timesteps(ode_timestepsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type simulation_timestep_size(simulation_timestep_sizeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type simulation_timesteps(simulation_timestepsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type bool_is_not_na_obsMat(bool_is_not_na_obsMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type number_of_available_obs(number_of_available_obsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type ukf_pars(ukf_parsSEXP);
    Rcpp::traits::input_parameter< const int >::type ng(ngSEXP);
    Rcpp::traits::input_parameter< const int >::type last_pred_id(last_pred_idSEXP);
    Rcpp::traits::input_parameter< const int >::type k_step_ahead(k_step_aheadSEXP);
    Rcpp::traits::input_parameter< const int >::type ode_solver(ode_solverSEXP);
    Rcpp::traits::input_parameter< const int >::type nsims(nsimsSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(ukf_simulate_rcpp(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, simulation_timestep_size, simulation_timesteps, bool_is_not_na_obsMat, number_of_available_obs, ukf_pars, ng, last_pred_id, k_step_ahead, ode_solver, nsims, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ctsmTMB_ekf_filter_rcpp", (DL_FUNC) &_ctsmTMB_ekf_filter_rcpp, 11},
    {"_ctsmTMB_ekf_predict_rcpp", (DL_FUNC) &_ctsmTMB_ekf_predict_rcpp, 13},
    {"_ctsmTMB_ekf_simulate_rcpp", (DL_FUNC) &_ctsmTMB_ekf_simulate_rcpp, 18},
    {"_ctsmTMB_calculate_filtering_observations", (DL_FUNC) &_ctsmTMB_calculate_filtering_observations, 5},
    {"_ctsmTMB_lkf_filter_rcpp", (DL_FUNC) &_ctsmTMB_lkf_filter_rcpp, 9},
    {"_ctsmTMB_lkf_predict_rcpp", (DL_FUNC) &_ctsmTMB_lkf_predict_rcpp, 11},
    {"_ctsmTMB_lkf_simulate_rcpp", (DL_FUNC) &_ctsmTMB_lkf_simulate_rcpp, 16},
    {"_ctsmTMB_test_return_list", (DL_FUNC) &_ctsmTMB_test_return_list, 1},
    {"_ctsmTMB_calculate_prediction_observations", (DL_FUNC) &_ctsmTMB_calculate_prediction_observations, 9},
    {"_ctsmTMB_calculate_simulation_observations", (DL_FUNC) &_ctsmTMB_calculate_simulation_observations, 9},
    {"_ctsmTMB_build_simulation_returnlist", (DL_FUNC) &_ctsmTMB_build_simulation_returnlist, 5},
    {"_ctsmTMB_build_simulation_timelists", (DL_FUNC) &_ctsmTMB_build_simulation_timelists, 3},
    {"_ctsmTMB_ukf_filter_rcpp", (DL_FUNC) &_ctsmTMB_ukf_filter_rcpp, 12},
    {"_ctsmTMB_ukf_predict_rcpp", (DL_FUNC) &_ctsmTMB_ukf_predict_rcpp, 14},
    {"_ctsmTMB_ukf_simulate_rcpp", (DL_FUNC) &_ctsmTMB_ukf_simulate_rcpp, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_ctsmTMB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
