# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ekf_filter_rcpp <- function(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, any_available_obs, non_na_ids, ode_solver) {
    .Call('_ctsmTMB_ekf_filter_rcpp', PACKAGE = 'ctsmTMB', funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, any_available_obs, non_na_ids, ode_solver)
}

ekf_predict_rcpp <- function(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, any_available_obs, non_na_ids, ode_solver, last_pred_id, k_step_ahead) {
    .Call('_ctsmTMB_ekf_predict_rcpp', PACKAGE = 'ctsmTMB', funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, any_available_obs, non_na_ids, ode_solver, last_pred_id, k_step_ahead)
}

ekf_simulate_rcpp <- function(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, simulation_timestep_size, simulation_timesteps, any_available_obs, non_na_ids, ode_solver, last_pred_id, k_step_ahead, ng, nsims, seed) {
    .Call('_ctsmTMB_ekf_simulate_rcpp', PACKAGE = 'ctsmTMB', funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, simulation_timestep_size, simulation_timesteps, any_available_obs, non_na_ids, ode_solver, last_pred_id, k_step_ahead, ng, nsims, seed)
}

calculate_filtering_observations <- function(filtration_raw, funPtrs, inputMat, parVec, n_obs) {
    .Call('_ctsmTMB_calculate_filtering_observations', PACKAGE = 'ctsmTMB', filtration_raw, funPtrs, inputMat, parVec, n_obs)
}

lkf_filter_rcpp <- function(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, any_available_obs, non_na_ids) {
    .Call('_ctsmTMB_lkf_filter_rcpp', PACKAGE = 'ctsmTMB', funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, any_available_obs, non_na_ids)
}

lkf_predict_rcpp <- function(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, any_available_obs, non_na_ids, last_pred_id, k_step_ahead) {
    .Call('_ctsmTMB_lkf_predict_rcpp', PACKAGE = 'ctsmTMB', funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, any_available_obs, non_na_ids, last_pred_id, k_step_ahead)
}

lkf_simulate_rcpp <- function(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, simulation_timestep_size, simulation_timesteps, any_available_obs, non_na_ids, ng, last_pred_id, k_step_ahead, nsims, seed) {
    .Call('_ctsmTMB_lkf_simulate_rcpp', PACKAGE = 'ctsmTMB', funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, simulation_timestep_size, simulation_timesteps, any_available_obs, non_na_ids, ng, last_pred_id, k_step_ahead, nsims, seed)
}

test_return_list <- function(a) {
    .Call('_ctsmTMB_test_return_list', PACKAGE = 'ctsmTMB', a)
}

calculate_prediction_observations <- function(predMat, funPtrs, inputMat, parVec, n_states, n_obs, last_pred_id, k_ahead, compute_dispersion) {
    .Call('_ctsmTMB_calculate_prediction_observations', PACKAGE = 'ctsmTMB', predMat, funPtrs, inputMat, parVec, n_states, n_obs, last_pred_id, k_ahead, compute_dispersion)
}

calculate_simulation_observations <- function(simulation_raw_states, funPtrs, inputMat_T, parVec, n_states, n_obs, k_ahead, n_sims, seed) {
    .Call('_ctsmTMB_calculate_simulation_observations', PACKAGE = 'ctsmTMB', simulation_raw_states, funPtrs, inputMat_T, parVec, n_states, n_obs, k_ahead, n_sims, seed)
}

build_simulation_returnlist <- function(simulation_raw, time_vector, n_states, k_ahead, n_sims) {
    .Call('_ctsmTMB_build_simulation_returnlist', PACKAGE = 'ctsmTMB', simulation_raw, time_vector, n_states, k_ahead, n_sims)
}

build_simulation_timelists <- function(time_vector, n_forecasts, k_ahead) {
    .Call('_ctsmTMB_build_simulation_timelists', PACKAGE = 'ctsmTMB', time_vector, n_forecasts, k_ahead)
}

ukf_filter_rcpp <- function(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, bool_is_not_na_obsMat, number_of_available_obs, ukf_pars, ode_solver) {
    .Call('_ctsmTMB_ukf_filter_rcpp', PACKAGE = 'ctsmTMB', funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, bool_is_not_na_obsMat, number_of_available_obs, ukf_pars, ode_solver)
}

ukf_predict_rcpp <- function(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, bool_is_not_na_obsMat, number_of_available_obs, ukf_pars, last_pred_id, k_step_ahead, ode_solver) {
    .Call('_ctsmTMB_ukf_predict_rcpp', PACKAGE = 'ctsmTMB', funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, bool_is_not_na_obsMat, number_of_available_obs, ukf_pars, last_pred_id, k_step_ahead, ode_solver)
}

ukf_simulate_rcpp <- function(funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, simulation_timestep_size, simulation_timesteps, bool_is_not_na_obsMat, number_of_available_obs, ukf_pars, ng, last_pred_id, k_step_ahead, ode_solver, nsims, seed) {
    .Call('_ctsmTMB_ukf_simulate_rcpp', PACKAGE = 'ctsmTMB', funPtrs, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, simulation_timestep_size, simulation_timesteps, bool_is_not_na_obsMat, number_of_available_obs, ukf_pars, ng, last_pred_id, k_step_ahead, ode_solver, nsims, seed)
}

