# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@ export
execute_ekf_prediction <- function(f__R, g__R, dfdx__R, h__R, dhdx__R, hvar__R, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, bool_is_not_na_obsMat, number_of_available_obs, n, m, last_pred_id, k_step_ahead, ode_solver) {
    .Call('_sdeTMB_execute_ekf_prediction', PACKAGE = 'sdeTMB', f__R, g__R, dfdx__R, h__R, dhdx__R, hvar__R, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, bool_is_not_na_obsMat, number_of_available_obs, n, m, last_pred_id, k_step_ahead, ode_solver)
}

#'@ export
execute_ekf_simulation <- function(f__R, g__R, dfdx__R, h__R, dhdx__R, hvar__R, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, simulation_timestep_size, simulation_timesteps, bool_is_not_na_obsMat, number_of_available_obs, n, m, ng, last_pred_id, k_step_ahead, ode_solver, nsims) {
    .Call('_sdeTMB_execute_ekf_simulation', PACKAGE = 'sdeTMB', f__R, g__R, dfdx__R, h__R, dhdx__R, hvar__R, obsMat, inputMat, parVec, covMat, stateVec, ode_timestep_size, ode_timesteps, simulation_timestep_size, simulation_timesteps, bool_is_not_na_obsMat, number_of_available_obs, n, m, ng, last_pred_id, k_step_ahead, ode_solver, nsims)
}

zrnorm <- function(n) {
    .Call('_sdeTMB_zrnorm', PACKAGE = 'sdeTMB', n)
}

zsetseed <- function(s) {
    invisible(.Call('_sdeTMB_zsetseed', PACKAGE = 'sdeTMB', s))
}

